imports:
  - { resource: common.yml }
parameters:
  ps_accounts.firebase_api_key: 'AIzaSyBEm26bA2KR893rY68enLdVGpqnkoW2Juo'
  ps_accounts.svc_accounts_api_url: 'https://accounts-api.psessentials.net'
  ps_accounts.svc_accounts_ui_url: 'https://accounts.psessentials.net'
  ps_accounts.svc_billing_api_url: 'https://billing-api.distribution.prestashop.net'
  ps_accounts.sso_account_url: 'https://auth.prestashop.com/login'
  ps_accounts.sso_resend_verification_email_url: 'https://auth.prestashop.com/account/send-verification-email'
  ps_accounts.sentry_credentials: 'https://4c7f6c8dd5aa405b8401a35f5cf26ada@o298402.ingest.sentry.io/5354585'