<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'form.type.order.message' shared service.

return $this->services['form.type.order.message'] = new \PrestaShopBundle\Form\Admin\Sell\CustomerService\OrderMessageType();
