<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Api\\Client\\FirebaseClient'] = new \PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient(['api_key' => 'AIzaSyBEm26bA2KR893rY68enLdVGpqnkoW2Juo']);
