<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.bundle.form.admin.sell.attachment.attachment' shared service.

$this->services['prestashop.bundle.form.admin.sell.attachment.attachment'] = $instance = new \PrestaShopBundle\Form\Admin\Sell\Attachment\AttachmentType();

$instance->setTranslator(${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});

return $instance;
