<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\PayloadDecorator'] = new \PrestaShop\Module\PsEventbus\Decorator\PayloadDecorator(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\DateFormatter']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\DateFormatter'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\DateFormatter'] = new \PrestaShop\Module\PsEventbus\Formatter\DateFormatter())) && false ?: '_'});
