<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.adapter.attribute_group.command_handler.bulk_delete_attribute_group_handler' shared service.

return $this->services['prestashop.adapter.attribute_group.command_handler.bulk_delete_attribute_group_handler'] = new \PrestaShop\PrestaShop\Adapter\AttributeGroup\CommandHandler\BulkDeleteAttributeGroupHandler();
