<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ps_eventbus.db' shared service.

return $this->services['ps_eventbus.db'] = \Db::getInstance();
