<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_accounts.context' shared service.

return $this->services['ps_accounts.context'] = \Context::getContext();
