<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsEventbus\Service\ProxyService' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Service\\ProxyService'] = new \PrestaShop\Module\PsEventbus\Service\ProxyService(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Api\\EventBusProxyClient']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Api\\EventBusProxyClient'] : $this->load('getEventBusProxyClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\JsonFormatter']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\JsonFormatter'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\JsonFormatter'] = new \PrestaShop\Module\PsEventbus\Formatter\JsonFormatter())) && false ?: '_'});
