<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Service\ShopTokenService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\ShopTokenService'] = new \PrestaShop\Module\PsAccounts\Service\ShopTokenService(${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Api\\Client\\FirebaseClient']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Api\\Client\\FirebaseClient'] : ($this->services['PrestaShop\\Module\\PsAccounts\\Api\\Client\\FirebaseClient'] = new \PrestaShop\Module\PsAccounts\Api\Client\FirebaseClient(['api_key' => 'AIzaSyBEm26bA2KR893rY68enLdVGpqnkoW2Juo']))) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsAccounts\\Repository\\ConfigurationRepository']) ? $this->services['PrestaShop\\Module\\PsAccounts\\Repository\\ConfigurationRepository'] : $this->load('getConfigurationRepositoryService.php')) && false ?: '_'});
