<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Service\SsoService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\SsoService'] = new \PrestaShop\Module\PsAccounts\Service\SsoService(['sso_resend_verification_email_url' => 'https://auth.prestashop.com/account/send-verification-email', 'sso_account_url' => 'https://auth.prestashop.com/login']);
