<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsEventbus\Service\SynchronizationService' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Service\\SynchronizationService'] = new \PrestaShop\Module\PsEventbus\Service\SynchronizationService(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\EventbusSyncRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\EventbusSyncRepository'] : $this->load('getEventbusSyncRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\IncrementalSyncRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\IncrementalSyncRepository'] : $this->load('getIncrementalSyncRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Service\\ProxyService']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Service\\ProxyService'] : $this->load('getProxyServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\PayloadDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\PayloadDecorator'] : $this->load('getPayloadDecoratorService.php')) && false ?: '_'});
